spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  main:
    banner-mode: off
server:
  port: 8080
  error:
    include-stacktrace: never
